### ISSUE TITLE
Failed to add Head to Hologram 1.20.4

### ISSUE THREAD

**Issue by JanReich** [DecentSoftware-eu/DecentHolograms#192]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

1. Install DecentHolograms...
2. Create New Hologram
3. Add A line with an Playerhead (Work in previous Versions, but after we updatet decentholograms and the server to 1.20.4 when get the Error (look at pastebin)

Sourcecode where we use the Decenthologram API: https://pastebin.com/46Kt7DPC
The resulting error: https://pastebin.com/wLTuALRt

It would be realy nice if you could manage to fix this issue.

### Solution

Caused by: java.lang.NoSuchMethodError: 'java.lang.String com.mojang.authlib.properties.Property.getValue()'

It looks like the method dosent exists in 1.20.4 anymore

### Server Version

1.20.4

### Client Version

1.20.4

### Plugin Version

2.8.6

### Log

https://pastebin.com/wLTuALRt

**Comment by Andre601** [comment]
This is already fixed in the current code of DH:
https://github.com/DecentSoftware-eu/DecentHolograms/blob/main/src/main/java/eu/decentsoftware/holograms/api/utils/items/SkullUtils.java#L74-L90

So it's already fixed, but just not yet released.

**Comment by TabZz147** [comment]
When could you expect an update? That would be really nice <3

**Comment by TabZz147** [comment]
hmm? :)

**Comment by d0by1** [comment]
This fix is present in version 2.8.7, enjoy.
